default: &default
  # Required license key associated with your New Relic account.
  license_key: <%= ENV['NEWRELIC_LICENSE_KEY'] %>

  # Your application name. Renaming here affects where data displays in New
  # Relic.  For more details, see https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/renaming-applications
  app_name: <%= ENV['NEWRELIC_APP_NAME'] || "Vangst Discourse (#{ENV['RAILS_ENV']})" %>

  distributed_tracing:
    enabled: true

  # To disable the agent regardless of other settings, uncomment the following:
  # agent_enabled: false

  # Logging level for log/newrelic_agent.log
  log_level: info


development:
  <<: *default
  app_name: Vangst Discourse (Development)

test:
  <<: *default
  # It doesn't make sense to report to New Relic from automated test runs.
  monitor_mode: false

production:
  <<: *default
